- name: Wait for emulator to fully boot
  run: |
    adb start-server
    echo "Waiting for emulator..."
    # wait up to 3 minutes
    for i in {1..36}; do
      state=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
      if [ "$state" = "1" ]; then
        echo "✅ Emulator booted"
        break
      fi
      echo "Waiting... $i/36"
      sleep 5
    done
    adb devices -l
