name: PotatoVPN IP Capture

on:
  workflow_dispatch: {}

jobs:
  run-emulator-and-capture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Start Android emulator (API 33, x86_64)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          emulator-options: -no-window -gpu swiftshader_indirect
          force-avd-creation: true
          script: |
            echo "emulator started"

      - name: Wait for device
        run: |
          adb wait-for-device
          adb devices

      - name: Install APK (ensure potato.apk exists in repo root)
        run: |
          if [ ! -f "./potato.apk" ]; then
            echo "ERROR: potato.apk not found at repo root. Upload potato.apk or change workflow path." >&2
            exit 1
          fi
          adb install -r ./potato.apk

      - name: Give app a moment to settle
        run: sleep 3

      - name: Run capture script
        env:
          ADB_PATH: adb
        run: |
          python3 --version
          python3 tools/potato_adb_capture.py

      - name: Upload result artifact
        uses: actions/upload-artifact@v4
        with:
          name: potato_vpn_ips
          path: potato_vpn_ips.csv
